<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerA9Rqfdx\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerA9Rqfdx/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerA9Rqfdx.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerA9Rqfdx\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerA9Rqfdx\App_KernelDevDebugContainer([
    'container.build_hash' => 'A9Rqfdx',
    'container.build_id' => '99b4d703',
    'container.build_time' => 1683640974,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerA9Rqfdx');
