<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSSO0olS\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSSO0olS/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerSSO0olS.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerSSO0olS\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerSSO0olS\App_KernelDevDebugContainer([
    'container.build_hash' => 'SSO0olS',
    'container.build_id' => 'a0ad927d',
    'container.build_time' => 1683273528,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSSO0olS');
