<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWzx2HPx\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWzx2HPx/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerWzx2HPx.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerWzx2HPx\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerWzx2HPx\App_KernelDevDebugContainer([
    'container.build_hash' => 'Wzx2HPx',
    'container.build_id' => 'a7caa431',
    'container.build_time' => 1683297612,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWzx2HPx');
