<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'api_app_projet_produits' => [[], ['_controller' => 'App\\Controller\\ProjetController::index'], [], [['text', '/api/projet/produit']], [], [], []],
    'api_app_projet_categories' => [[], ['_controller' => 'App\\Controller\\ProjetController::index_cat'], [], [['text', '/api/projet/category']], [], [], []],
    'api_app_projet_fournisseurs' => [[], ['_controller' => 'App\\Controller\\ProjetController::indexFour'], [], [['text', '/api/projet/fournisseur']], [], [], []],
    'api_project_produit_new' => [[], ['_controller' => 'App\\Controller\\ProjetController::new'], [], [['text', '/api/projet/produit']], [], [], []],
    'api_project_categorie_new' => [[], ['_controller' => 'App\\Controller\\ProjetController::new_Categorie'], [], [['text', '/api/projet/category']], [], [], []],
    'api_project_fournisseur_new' => [[], ['_controller' => 'App\\Controller\\ProjetController::new_Fournisseur'], [], [['text', '/api/projet/fournisseur']], [], [], []],
    'api_project_show' => [['id'], ['_controller' => 'App\\Controller\\ProjetController::show'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/projet/produit']], [], [], []],
    'api_project_categorie_show' => [['id'], ['_controller' => 'App\\Controller\\ProjetController::show_Categorie'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/projet/category']], [], [], []],
    'api_project_show_fournisseur' => [['id'], ['_controller' => 'App\\Controller\\ProjetController::show_Fournisseur'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/projet/fournisseur']], [], [], []],
    'api_project_edit' => [['id'], ['_controller' => 'App\\Controller\\ProjetController::edit'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/projet/produit']], [], [], []],
    'api_project_edit_categorie' => [['id'], ['_controller' => 'App\\Controller\\ProjetController::edit_fournisseur'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/projet/fournisseur']], [], [], []],
    'api_project_delete_produit' => [['id'], ['_controller' => 'App\\Controller\\ProjetController::delete_produit'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/projet/produit']], [], [], []],
    'api_project_delete_categorie' => [['id'], ['_controller' => 'App\\Controller\\ProjetController::delete_categorie'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/projet/category']], [], [], []],
    'api_project_delete_fournisseur' => [['id'], ['_controller' => 'App\\Controller\\ProjetController::delete_fournisseur'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/projet/fournisseur']], [], [], []],
    'api_app_security' => [[], ['_controller' => 'App\\Controller\\SecurityController::index'], [], [['text', '/api/register']], [], [], []],
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    'api_login_check' => [[], [], [], [['text', '/api/login_check']], [], [], []],
];
